### ISSUE TITLE
login issue  401 - Unauthorized

### ISSUE THREAD

**Issue by vasilywang** [ThePantsThief/SnapchatKit#1]
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>401 UNAUTHORIZED</title>
</head>
<body text=#000000 bgcolor=#ffffff>

<h1>Error: UNAUTHORIZED</h1>

</body></html>

**Comment by NSExceptional** [comment]
This is happening with other libraries too, started the other day. I think they may be blocking our user agent or something. I'll close this if / when it starts working again.

**Comment by NSExceptional** [comment]
Kinda fixed. It'll give you a "login temporarily failed" error every other time you try to sign in.

**Comment by KiranPanesar** [comment]
@ThePantsThief I am seeing the "Login temporarily failed" stuff too. It happens maybe 50% of the time. Did you have any ideas on how to avoid this? Or even a repeatable pattern/behaviour which causes this?

**Comment by NSExceptional** [comment]
I'm just not making the request properly. I'm working with some others who have their own snapchat clients but they're all using AFNetworking and they have no idea what I'm doing wrong either. In the meantime, anyone using this library will just have to try repeatedly :/

I haven't gotten around to making an issue for this so I'll just leave it open until it gets figured out.

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
@ThePantsThief  Could you point to some libraries that are working consistently? I can look into porting the functionality.

**Comment by NSExceptional** [comment]
https://github.com/mgp25/SC-API Thanks!

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
I thought there were some which were in Objective-C and using AFNetworking?

**Comment by NSExceptional** [comment]
No public libraries, mine is the only (semi) working public objc Snapchat API implementation to my knowledge. You can ask Harry https://github.com/harrygulliford if he would be willing to share any of his code with you; he wants to migrate his app to SnapchatKit so it would be beneficial to all three of us if he would.

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
@ThePantsThief Noticed that this was closed. Is it fixed?

**Comment by NSExceptional** [comment]
It should be, yes!

## 

Tanner Bennett
