### ISSUE TITLE
Why need AFNetworking?

### ISSUE THREAD

**Issue by Shun87** [ThePantsThief/SnapchatKit#13]
As metioned in Readme:"Installation

Add SnapchatKit to your podfile:
pod 'SnapchatKit'
Or add the source files in /Pods to your project, as well as AFNetworking and SSZipArchive. 
".

But snapchatKit doesn't  depend on AFNetworking, why we need copy AFNetworking to our project?

**Comment by NSExceptional** [comment]
Whoops, I need to remove that. SnapchatKit has no external dependencies, correct.

It may also be broken at the moment, FYI. Google started doing something new that broke all 3rd party clients.

## 

Tanner Bennett

**Comment by Shun87** [comment]
Oh...NO, do you know any other way except google to trick snapchat?

**Comment by NSExceptional** [comment]
Google accounts are necessary to trick Snapchat into thinking we're using the first party client.

## 

Tanner Bennett
