### ISSUE TITLE
"Your login temporarily failed"

### ISSUE THREAD

**Issue by KiranPanesar** [ThePantsThief/SnapchatKit#14]
For the past few days I've been running into the following error when trying to sign in.

`Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)`

The error is being triggered in the network request for:
`- (void)signInWithData:(NSDictionary *)loginData username:(NSString *)username password:(NSString *)password completion:(DictionaryBlock)completion;`

Any ideas?

**Comment by NSExceptional** [comment]
A fix will be out in a few days. Stay tuned!

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
Can you share what the issue is? We wanted to launch an update to our app today/tomorrow with he Snapchat integration.

**Comment by NSExceptional** [comment]
You use SnapchatKit in your app? Awesome :)

Google started checking for valid droid guard data when requesting attestation, so now we have to spoof that too (and we weren't before). There's already a fix in the PHP library and I'm in the process of porting it over. I'll try and get it done tonight for ya

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
Gonna be using it in the next version :) I've actually made a few modifications to the SnapchatKit codebase locally to fit our use-case. Might be useful for others, so I'll chuck them into a PR at some point in the next few days.

Shoot me an email if you need a hand with any of the spoofing changes.

**Comment by NSExceptional** [comment]
What changes did you make? I try to design SnapchatKit to be as flexible as possible, if you have a case that's more specific than anything it currently offers I might be able to make it official :)

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
The main one is the ability for bringing your own Google Token. We generate a Google auth token elsewhere in the app, so wanted to just send that same token through rather than re-prompting for credentials.

Also, we wanted to be able to set a custom URL for generating the client auth token (instead of casper.io). So we made that customisable in our system.

**Comment by NSExceptional** [comment]
Ahhhh. I could implement those for sure.

## 

Tanner Bennett

**Comment by KiranPanesar** [comment]
Hey, any idea of when the fix will be out? Any way I can help expedite it?
