### ISSUE TITLE
getAuthTokenForGmail error

### ISSUE THREAD

**Issue by Shun87** [ThePantsThief/SnapchatKit#16]
When I login, I got this error message:Domain=SnapchatKit Code=1 "Could not retrieve Google auth token." UserInfo={NSLocalizedDescription=Could not retrieve Google auth token., NSLocalizedFailureReason=Could not retrieve Google auth token.}

**Comment by NSExceptional** [comment]
Are you using the latest version? (0.3.5)

I just updated it a few hours ago

## 

Tanner Bennett

**Comment by Shun87** [comment]
YES, I have updated it, but the same error

**Comment by NSExceptional** [comment]
Are you supplying a valid gmail account? Try using a different one

## 

Tanner Bennett

**Comment by Shun87** [comment]
After I use another gmail account, it works, but I got a assert like this" *** Assertion failure in -[SKClient getAttestation:password:ts:callback:], /Users/tsinglink/GitHub/SnapUploader/Pods/SnapchatKit/Pod/Classes/Networking/SKClient.m:328
2015-10-06 17:39:16.439 SnapUploader[4558:57211] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must have a valid API key from https://clients.casper.io to sign in.'
"

**Comment by NSExceptional** [comment]
Read the error, follow the instructions.

## 

Tanner Bennett

**Comment by Shun87** [comment]
After I use another gmail account, it works. But I got a assert like this **\* Assertion failure in -[SKClient getAttestation:password:ts:callback:], Pods/SnapchatKit/Pod/Classes/Networking/SKClient.m:328
 **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You must have a valid API key from https://clients.casper.io to sign in.'

**Comment by Shun87** [comment]
Thank you

**Comment by NSExceptional** [comment]
Also, see the new properties on SKClient: casperAPIKey and casperAPISecret. 

## 

Tanner Bennett

**Comment by NSExceptional** [comment]
You're very welcome :)

## 

Tanner Bennett
