### ISSUE TITLE
Poblems about restoreSessionWithUsername 

### ISSUE THREAD

**Issue by Shun87** [ThePantsThief/SnapchatKit#17]
I found this comment:"Use this to restore a session that ended within the last hour. The google auth token must be re-generated every hour." But I want to know how can I re-generate a google auth token? getAuthTokenForGmail is private.

**Comment by NSExceptional** [comment]
Sign in again. 

Tanner Bennett

**Comment by Shun87** [comment]
Thank you, When I need to use restoreSessionWithUsername
