### ISSUE TITLE
send image 415 response code 

### ISSUE THREAD

**Issue by Shun87** [ThePantsThief/SnapchatKit#18]
When I try to send a image, I got the error message like this:Error Domain=SnapchatKit Code=415 "415 UNSUPPORTED_MEDIA_TYPE" UserInfo={NSLocalizedDescription=415 UNSUPPORTED_MEDIA_TYPE, NSLocalizedFailureReason=415 UNSUPPORTED_MEDIA_TYPE};

But sending video works well.

**Comment by NSExceptional** [comment]
Well what kind of image is it?

Tanner Bennett

**Comment by Shun87** [comment]
.png format,  I pick it from my camera roll

**Comment by Shun87** [comment]
I found upload is success, but failed when  postTo:SKEPSnaps.send

**Comment by liamcottle** [comment]
Snapchat only support JPG images.

**Comment by Shun87** [comment]
Thanks
