### ISSUE TITLE
SnapchatKit for iOS

### ISSUE THREAD

**Issue by sambudda** [ThePantsThief/SnapchatKit#2]
A little off-topic but can you make a similar project for iOS / iPhone? If you already do that then let me know and I will download that. Thanks.

**Comment by NSExceptional** [comment]
I'm not sure what you mean, SnapchatKit can be used on iOS as is

## 

Tanner Bennett

**Comment by NSExceptional** [comment]
If you want to use it on iOS, just copy the entire SnapchatKit folder (the one in the same folder as main.m) to your project and import SnapchatKit.h

## 

Tanner Bennett

**Comment by sambudda** [comment]
What I mean is that the only option I see when I run and build is for Mac only.

Let me try your suggestion. 

![screen shot 2015-06-21 at 10 00 24 am](https://cloud.githubusercontent.com/assets/3536867/8271889/83b8fd48-17fc-11e5-9ec5-baf04b2202b3.png)

**Comment by NSExceptional** [comment]
You'll need to copy the SnapchatKit folder to an existing iOS project; I don't have an example yet. main.m demonstrates how to use some of the APIs. 

FYI Snapchat changed something that broke it so we can't sign in at the moment

## 

Tanner Bennett

**Comment by sambudda** [comment]
Just tried your suggestion but it gives a build error. Module AppKit not found

Ok, thanks for the update on it not working. Just curiously even if I could get it to compile then I would need to do a lot of coding (using your project as an example) to have to setup in iOS, i.e. login screen, results page etc, correct?

See pics

![screen shot 2015-06-21 at 10 09 53 am](https://cloud.githubusercontent.com/assets/3536867/8271922/0b49e65e-17fe-11e5-806d-7d2b73a3652b.png)
![screen shot 2015-06-21 at 10 10 58 am](https://cloud.githubusercontent.com/assets/3536867/8271923/0b4a70ba-17fe-11e5-945c-bb332807ddb8.png)

**Comment by NSExceptional** [comment]
Hmmm comment out the import. I may have done that for debugging purposes. 

## 

Tanner Bennett

**Comment by sambudda** [comment]
commenting that out raises a whole set of other build issues. Thanks for trying. If you ever do decide to have a iOS version of this project available then that would be very cool. Please do ping me if you do so. Thank you.

![screen shot 2015-06-21 at 10 18 26 am](https://cloud.githubusercontent.com/assets/3536867/8271942/1864a7ec-17ff-11e5-856d-1e241d4f4953.png)

**Comment by NSExceptional** [comment]
Import UIKit

## 

Tanner Bennett

**Comment by NSExceptional** [comment]
I need to make it so that it doesn't require AppKit or UIKit haha

## 

Tanner Bennett
