### ISSUE TITLE
signInWithUsername not work now!

### ISSUE THREAD

**Issue by Shun87** [ThePantsThief/SnapchatKit#20]
Hello, I got the error message like this:signInWithUsername Error Domain=SnapchatKit Code=1 "Could not retrieve attestation." UserInfo={NSLocalizedDescription=Could not retrieve attestation., NSLocalizedFailureReason=Could not retrieve attestation

**Comment by NSExceptional** [comment]
It's broken atm :( Liam Cottle is working on a fix 

## 

Tanner Bennett

**Comment by Shun87** [comment]
Casper API is working now

**Comment by NSExceptional** [comment]
Probably so! I apologize, I haven't had time to look into it with school. I'll have an update out after I get home from uni for winter break, I get home on the 16th

## 

Tanner Bennett

**Comment by Shun87** [comment]
Hello, When I use restoreSessionWithUsername method, I got a error message: Error Domain=SnapchatKit Code=401 "401 UNAUTHORIZED" UserInfo={NSLocalizedDescription=401 UNAUTHORIZED, NSLocalizedFailureReason=401 UNAUTHORIZED}. The parameter "authToken" and "googleAuthToken" is valid. Do you know why?

**Comment by Shun87** [comment]
It works well 2 days ago, but now it doesn't work anymore. Error: Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :

**Comment by NSExceptional** [comment]
Liam has moved to the iOS API which is private for now. If or when it becomes public, SnapchatKit will now work again.
