### ISSUE TITLE
function device() error RESULT: 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by Shun87** [ThePantsThief/SnapchatKit#21]
Hello, I have keep a valid googleAuthToken and authToken, when I sign in, it runs error returned by device(). the error message like this :RESULT: 401 UNAUTHORIZED

**Comment by NSExceptional** [comment]
Google auth tokens expire every hour. Are you using a fresh one?

## 

Tanner Bennett

**Comment by Shun87** [comment]
Thank you, it's Ok now.
