### ISSUE TITLE
Trying again...  not getting result

### ISSUE THREAD

**Issue by faizankhananics** [ThePantsThief/SnapchatKit#24]
i am getting null result while  trying again ... well i did gave all the field as per Readme.md file

**Comment by NSExceptional** [comment]
Login is not working at the moment

## 

Tanner Bennett

**Comment by faizankhananics** [comment]
so how we will proceed the app .  Need steps or description

**Comment by NSExceptional** [comment]
Waiting on Liam Cottle to update his API. Everything will be put to a halt until it's working again.

## 

Tanner Bennett

**Comment by NSExceptional** [comment]
Liam has moved to the iOS API which is private for now. If or when it becomes public, SnapchatKit will now work again.
