### ISSUE TITLE
Looking for someone to change my params. 

### ISSUE THREAD

**Issue by h4ck1th4rd** [ThePantsThief/SnapchatKit#32]
ok, thank you. cheers

**Comment by NSExceptional** [comment]
Are you using the Casper API at all? Or did you mean you're generating the header tokens from a jailbroken device?

**Comment by mzaboss** [comment]
Yes, I just need now to send snaps. What I did wrong?

**Comment by NSExceptional** [comment]
Not sure. Study my code I guess, I don't have time to look at yours I'm sorry, I'm not good with JavaScript
