### ISSUE TITLE
Up to date

### ISSUE THREAD

**Issue by danielbronder** [ThePantsThief/SnapchatKit#34]
Is this kit still up to date with the current version and security of Snapchat, because the last commit was 8 months ago.

**Comment by NSExceptional** [comment]
Most methods still work, yes. Please open an issue if you find something that doesn't work (besides Liam's API timing out)

**Comment by danielbronder** [comment]
Do you when Liams API is available? I would like te register, but unfortunately I can't. So I have to wait to use this kit.

**Comment by NSExceptional** [comment]
It's very pricey… and it's the only way to use this kit unfortunately

**Comment by danielbronder** [comment]
Whats is the price exactly? I couldn't find it. If it is  too expensive I have to find another way to play around with the Snapchat API. Reverse engineer the app myself, which is a skill I do not possess.

**Comment by NSExceptional** [comment]
There's a link to the site in the readme.
