### ISSUE TITLE
SKClient getGoogleCloudMessagingIdentifier: always errors

### ISSUE THREAD

**Issue by transitive-bullshit** [ThePantsThief/SnapchatKit#7]
Always returns the same body `PHONE_REGISTRATION_ERROR`

Any idea what might be the cause?

**Comment by NSExceptional** [comment]
No idea, could it be related to the other issue?

The value of that method isn't actually necessary, but I forgot that when I implemented it. I just pushed a commit which ignores the result of that method if it fails. You can use it directly by modifying your podfile like so: `pod 'SnapchatKit', :git => 'https://github.com/ThePantsThief/SnapchatKit.git'` until I update the pod again.

**Comment by transitive-bullshit** [comment]
It's not related to the spaces thing; I've verified the same error in my node version.

Thanks for the update!
