### ISSUE TITLE
Spaces in URLs

### ISSUE THREAD

**Issue by transitive-bullshit** [ThePantsThief/SnapchatKit#8]
All of the main auth URLs in the repo contain spaces after the protocol making them invalid if the repo is run as-is.

E.g. `https: //android.clients.google.com/c2dm/register3`

I'm guessing this is intentional, but I'm not sure why.  @ThePantsThief?

**Comment by NSExceptional** [comment]
There's no spaces here, [line 284](https://github.com/ThePantsThief/SnapchatKit/blob/master/Pod/Classes/Networking/SKClient.m), that's weird…

**Comment by transitive-bullshit** [comment]
Hmmm, yeah that is weird; thought I had a fresh checkout.
